packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@wagmi/connectors": "6.2.0"

allowBuilds:
  "@reown/appkit": false
  bufferutil: false
  esbuild: true
  keccak: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - turbo@2.11.4
